//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMSDevelopmentApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class appoinment
    {
        public int appoinment_id { get; set; }
        public Nullable<int> patient_id { get; set; }
        public string appoinment_date { get; set; }
        public string appoinment_time { get; set; }
        public Nullable<int> department_id { get; set; }
        public Nullable<int> doctor_id { get; set; }
        public string purpose { get; set; }
        public string patient_type { get; set; }
        public string appoinment_type { get; set; }
    }
}
