//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMSDevelopmentApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bank
    {
        public int bank_id { get; set; }
        public string bank_name { get; set; }
        public string branch_name { get; set; }
        public string branch_address { get; set; }
        public string bank_account_no { get; set; }
        public Nullable<int> hospital_id { get; set; }
    }
}
