//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMSDevelopmentApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class blood_donation
    {
        public int blood_donation_id { get; set; }
        public Nullable<int> donor_id { get; set; }
        public Nullable<int> donation_place_id { get; set; }
        public Nullable<System.DateTime> donation_date { get; set; }
        public Nullable<int> donate_whom { get; set; }
        public Nullable<int> no_of_bag { get; set; }
    }
}
