//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMSDevelopmentApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class discharge
    {
        public int discharge_id { get; set; }
        public Nullable<int> patient_id { get; set; }
        public Nullable<int> appoinment_id { get; set; }
        public string discharge_date { get; set; }
        public Nullable<int> discharge_type_id { get; set; }
        public string advice_on_discharge { get; set; }
        public string condition_during_discharge { get; set; }
        public Nullable<int> discharge_by_id { get; set; }
    }
}
