//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMSDevelopmentApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class doctor
    {
        public int doctor_id { get; set; }
        public Nullable<int> department_id { get; set; }
        public string doctor_fees { get; set; }
        public Nullable<int> doctor_appoinment_count { get; set; }
        public string doctor_available_time_from { get; set; }
        public string doctor_available_time_to { get; set; }
        public string available { get; set; }
        public Nullable<int> employee_id { get; set; }
        public Nullable<int> doctor_registration_number { get; set; }
    }
}
