//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMSDevelopmentApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class doctor_schedule
    {
        public int doctor_schdule_id { get; set; }
        public Nullable<int> department_id { get; set; }
        public Nullable<int> doctor_id { get; set; }
        public Nullable<int> shif_type_id { get; set; }
        public string sat { get; set; }
        public string sun { get; set; }
        public string mon { get; set; }
        public string tues { get; set; }
        public string wed { get; set; }
        public string thurs { get; set; }
        public string fri { get; set; }
    }
}
