//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMSDevelopmentApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class drug_allergies
    {
        public int drug_allergies_id { get; set; }
        public string drug_allergies_name { get; set; }
        public string drug_allergies_description { get; set; }
    }
}
