//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMSDevelopmentApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int employee_id { get; set; }
        public string employee_name { get; set; }
        public string joining_date { get; set; }
        public string designation { get; set; }
        public Nullable<int> department_id { get; set; }
        public Nullable<int> role_type_id { get; set; }
        public Nullable<int> nid { get; set; }
        public string employee_code { get; set; }
        public string employee_user_name { get; set; }
        public string employee_password { get; set; }
        public string employee_email { get; set; }
        public string employee_address { get; set; }
        public Nullable<int> employee_serial { get; set; }
        public Nullable<int> hospital_id { get; set; }
    }
}
