//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMSDevelopmentApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class module
    {
        public int module_id { get; set; }
        public string module_name { get; set; }
        public Nullable<int> module_sort { get; set; }
        public string module_url { get; set; }
        public Nullable<int> module_parent_id { get; set; }
        public string module_alias { get; set; }
        public string module_icon { get; set; }
    }
}
