//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMSDevelopmentApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient
    {
        public int patient_id { get; set; }
        public string user_name { get; set; }
        public string password { get; set; }
        public string full_name { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public Nullable<int> division_id { get; set; }
        public Nullable<int> district_id { get; set; }
        public string zip_code { get; set; }
        public string phone { get; set; }
        public Nullable<int> nid_id { get; set; }
        public Nullable<int> role_type_id { get; set; }
        public string gender { get; set; }
        public string dob { get; set; }
        public string status { get; set; }
    }
}
