//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMSDevelopmentApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient_tracking
    {
        public int patient_tracking_id { get; set; }
        public Nullable<int> patient_id { get; set; }
        public string status { get; set; }
        public string entry_date { get; set; }
        public string appoinment_date { get; set; }
        public string presscription_date { get; set; }
        public string admission_date { get; set; }
        public string invoice_date { get; set; }
        public string discharge_date { get; set; }
    }
}
