//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMSDevelopmentApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient_health_info
    {
        public int medical_id { get; set; }
        public Nullable<int> patient_id { get; set; }
        public string blood_group { get; set; }
        public string blood_pressure { get; set; }
        public Nullable<int> age { get; set; }
        public Nullable<double> weight { get; set; }
        public Nullable<double> height { get; set; }
    }
}
