//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMSDevelopmentApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient_emergency_contact
    {
        public int patient_emergency_id { get; set; }
        public string contact_person_name { get; set; }
        public string relation { get; set; }
        public string contact_person_mobile { get; set; }
        public Nullable<int> patient_id { get; set; }
    }
}
