//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMSDevelopmentApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class presscription_complaints_mapping
    {
        public int presscription_complaints_mapping_id { get; set; }
        public Nullable<int> presscription_id { get; set; }
        public string chief_complaints { get; set; }
        public string chief_complaints_duration { get; set; }
    }
}
