//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMSDevelopmentApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class presscription
    {
        public int prescription_id { get; set; }
        public Nullable<int> patient_id { get; set; }
        public Nullable<int> appoinment_id { get; set; }
        public Nullable<System.DateTime> presscription_date { get; set; }
        public string need_admission { get; set; }
        public Nullable<int> disease_id { get; set; }
    }
}
