//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMSDevelopmentApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class role_permission
    {
        public int role_permission_id { get; set; }
        public Nullable<int> role_type_id { get; set; }
        public Nullable<int> module_id { get; set; }
    }
}
