//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMSDevelopmentApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class shift_type
    {
        public int shift_type_id { get; set; }
        public string shift_type_name { get; set; }
        public string shift_from { get; set; }
        public string shift_to { get; set; }
        public Nullable<int> hospital_id { get; set; }
    }
}
