//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMSDevelopmentApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class super_admin
    {
        public int super_admin_id { get; set; }
        public string super_admin_name { get; set; }
        public string company_name { get; set; }
        public string company_address { get; set; }
        public string super_user_name { get; set; }
        public string super_password { get; set; }
    }
}
