//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMSDevelopmentApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ward
    {
        public int ward_id { get; set; }
        public string ward_no { get; set; }
        public string ward_name { get; set; }
        public Nullable<int> department_id { get; set; }
        public Nullable<int> total_bed { get; set; }
        public string ward_type { get; set; }
        public string ward_for_whom { get; set; }
        public Nullable<decimal> bed_cost { get; set; }
        public Nullable<int> floor_id { get; set; }
        public string wing { get; set; }
        public Nullable<int> assign_bed { get; set; }
        public Nullable<int> rest_bed { get; set; }
        public string ward_status { get; set; }
    }
}
